services:
  backend:
    container_name: samurai-backend
    image: samurai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      BASE_URL: "http://localhost:${BACKEND_PORT}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  frontend:
    container_name: samurai-frontend
    image: samurai-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      VITE_APP_API_URL: "http://localhost:${BACKEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  db:
    container_name: samurai-db
    image: postgres:17
    restart: on-failure:5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  pgdata:
networks:
  samurai-network:
